
all:
	make -C common/build/
	make -C logcat/build/
	make -C demoloop/build/
	make -C demo/build/

.PHONY:clean
clean:
	make clean -C common/build/
	make clean -C logcat/build/
	make clean -C demoloop/build/
	make clean -C demo/build/
